
package br.com.pitagoras.factory;

/**
 
 * -- MySQL Script generated by MySQL Workbench
-- Thu Jun 23 02:00:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pablogos` DEFAULT CHARACTER SET utf8 ;
USE `pablogos` ;

-- -----------------------------------------------------
-- Table `mydb`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pablogos`.`Candidato` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Partido` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eleitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pablogos`.`Eleitor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Titulo_Eleitor` INT NULL,
  `CPF` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pablogos`.`Votos` (
  `ID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `Candidato_ID` INT NOT NULL,
  `Eleitor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Candidato_ID`, `Eleitor_ID`),
  INDEX `fk_Votos_Candidato_idx` (`Candidato_ID` ASC) VISIBLE,
  INDEX `fk_Votos_Eleitor1_idx` (`Eleitor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Votos_Candidato`
    FOREIGN KEY (`Candidato_ID`)
    REFERENCES `pablogos`.`Candidato` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votos_Eleitor1`
    FOREIGN KEY (`Eleitor_ID`)
    REFERENCES `pablogos`.`Eleitor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

 * 
 */
public class pablogos {
    
}
